# spring project name
spring:
  application:
    name: web-management
  # set database connection configuration
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chen888888
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# configure log message, to see the spring transaction management logging
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug